trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    ls -l   # Agrega este paso para verificar la estructura del directorio
    npm run build
    ls -l dist  # Agrega este paso para verificar la existencia de archivos en el directorio de salida
  displayName: 'npm install and build'
